FORMAT: 1A
HOST: https://exchange.swisschain.io


# Swisschain - Exchange

Exchange is an API allowing the broker to setup exchange with trading between any asset and track account balances.

# API usage

## Allowed HTTP Verbs:
- `PUT` : Updates a resource 
- `POST` : Creates a resource
- `GET` : Gets a resource or list of resources
- `DELETE` : Deletes a resource

## Description Of Usual Server Responses:
- 200 `OK` : the request was successful.
- 201 `Created` : the request was successful and a resource was created.
- 204 `No Content` : the request was successful but there is no representation to return.
- 400 `Bad Request` : the request has invalid or missing required parameters.
- 401 `Unauthorized` : authentication failed.
- 403 `Forbidden` : access denied.
- 404 `Not Found` : resource was not found.

## Authorization

TODO

## Pagination

TODO

## Error responses

TODO

## Asset [/api/asset/public-assets{?pageSize}]

Asset controller allow broker configuration assets for his exchange.

---

+ Attributes (object)
    + id: `8cea5fd7-42d4-40ac-907d-5856eacf6ab6` (string) - Asset unique ID. 
    + name: "USD" (string) - Name of asset.
    + description: "U.S. dollar" (string) - Description of asset
    + accuracy: 2 (number) - Counts of numbers after the comma
    + isDisabled: false (boolean) - Asset state
    + created: `2020-03-07T11:52:30.396827Z` (string) - Date & time of created acsset. Time zone: UTC+0. Format: ICO 8601.
    + modified: `2020-03-07T11:52:30.396827Z` (string) - Date & time of last modified asset. Time zone: UTC+0. Format: ICO 8601.
    

### Get List All Assets [GET]

Get a list of all listed assets.

+ Parameters
    + pageSize (optional, Number) - Count item on page

+ Request 
    + Headers

            Authorization: Bearer <put your api key>


+ Response 200 (application/json)

        [
            {
                "items": [
                    {
                        "id": "11542",
                        "name": "BTC",
                        "description": "Bitcoin",
                        "accuracy": 18,
                        "isDisabled": false,
                        "created": "2020-03-07T11:52:30.396827Z",
                        "modified": "2020-03-07T11:52:30.396827Z"
                    }, 
                    {
                        "id": "8cea5fd7-42d4-40ac-907d-5856eacf6ab6",
                        "name": "USD",
                        "description": "U.S. dollar",
                        "accuracy": 2,
                        "isDisabled": true,
                        "created": "2020-03-07T11:52:30.396827Z",
                        "modified": "2020-03-07T11:52:30.396827Z"
                    }
                ]
            }
        ]

### Create a New Asset [POST]

Create and listing new asset.

+ Request (application/json)

    + Headers

                Authorization: Bearer <put your api key>
    
    + Body
    
            {
                "id": "8cea5fd7-42d4-40ac-907d-5856eacf6ab6",
                "name": "USD",
                "description": "U.S. dollar",
                "accuracy": 2,
                "isDisabled": true,
            }

+ Response 200 (application/json)

    + Body

            {
                "id": "8cea5fd7-42d4-40ac-907d-5856eacf6ab6",
                "name": "USD",
                "description": "U.S. dollar",
                "accuracy": 2,
                "isDisabled": true,
                "created": "2020-03-07T11:52:30.396827Z",
                "modified": "2020-03-07T11:52:30.396827Z"
            }
            
### Update existing Asset [PUT]

Update parameters for the existing asset.

+ Request (application/json)

    + Headers

            Authorization: Bearer <put your api key>
    
    + Body
    
            {
                "id": "8cea5fd7-42d4-40ac-907d-5856eacf6ab6",
                "name": "USD",
                "description": "U.S. dollar",
                "accuracy": 2,
                "isDisabled": true
            }

+ Response 204 (application/json)

### Get Asset [GET/api/asset/public-assets/{assetId}]

Get a asset by ID

+ Parameters
    + assetId (string) - Asset qniquie ID
    
+ Request
    + Headers

            Authorization: Bearer <put your api key>


+ Response 200 (application/json)

        {
            "id": "11542",
            "name": "BTC",
            "description": "Bitcoin",
            "accuracy": 18,
            "isDisabled": false,
            "created": "2020-03-07T11:52:30.396827Z",
            "modified": "2020-03-07T11:52:30.396827Z"
        }
        
### Delete existing Asset [DELETE/api/asset/public-assets/{assetId}]

Delete existing asset from exchange

+ Parameters
    + assetId (string) - Asset qniquie ID
    
+ Request 
    + Headers

            Authorization: Bearer <put your api key>

+ Response 204 


## AssetPair [/api/asset/public-asset-pairs]

AssetPair controller allow broker configuration asset pair for his exchange.

---

+ Attributes (object)

    + id: `8cea5fd7-42d4-40ac-907d-5856eacf6ab6` (string) - Asset pair unique ID. 
    + name: "USD" (string) - Name of asset pair.
    + baseAssetId: "BTC" (string) - Name of base asset in pair.
    + quotingAssetId: `8cea5fd7-42d4-40ac-907d-5856eacf6ab6` (string) - Name of quoting asst in pair.
    + minVolume: 0.000001 (number) - Min volume for order
    + maxVolume: 40 (number) - Max volume for order
    + maxOppositeVolume: 100000 (number) - Max volume in quote asset for order
    + marketOrderPriceThreshold: 15 (number) - Allowable slippage for a market order in %
    + accuracy: 2 (number) - Counts of numbers after the comma in price
    + isDisabled: false (boolean) - Asset pair state
    + created: `2020-03-07T11:52:30.396827Z` (string) - Date & time of created acsset. Time zone: UTC+0. Format: ICO 8601.
    + modified: `2020-03-07T11:52:30.396827Z` (string) - Date & time of last modified asset. Time zone: UTC+0. Format: ICO 8601.
    

### Get list of all asset pairs [GET/api/asset/public-asset-pairs{?limit}]

Get a list of all listed asset pairs.

+ Parameters
    + limit (optional, number) - Count item on page

+ Request 
    + Headers

            Authorization: Bearer <put your api key>


+ Response 200 (application/json)

        [
            {
                "items": [
                    {
                        "id": "11542",
                        "name": "BTC",
                        "description": "Bitcoin",
                        "accuracy": 18,
                        "isDisabled": false,
                        "created": "2020-03-07T11:52:30.396827Z",
                        "modified": "2020-03-07T11:52:30.396827Z"
                    }, 
                    {
                        "id": "8cea5fd7-42d4-40ac-907d-5856eacf6ab6",
                        "name": "USD",
                        "description": "U.S. dollar",
                        "accuracy": 2,
                        "isDisabled": true,
                        "created": "2020-03-07T11:52:30.396827Z",
                        "modified": "2020-03-07T11:52:30.396827Z"
                    }
                ]
            }
        ]
        [
            {
                "id": "BTCUSD",
                "name": "BTCUSD",
                "baseAssetId": "BTC",
                "quotingAssetId": "USD",
                "accuracy": 3,
                "minVolume": 1e-8,
                "maxVolume": 10001,
                "maxOppositeVolume": 10001,
                "marketOrderPriceThreshold": 10001,
                "isDisabled": false,
                "created": "2020-03-07T12:01:16.959924Z",
                "modified": "2020-03-20T10:46:45.440441Z"
            },
            {
                "id": "9aea6fd7-42d4-40ac-907d-5856eacf6ee8",
                "name": "BTCETH",
                "baseAssetId": "BTC",
                "quotingAssetId": "8cea5fd7-42d4-40ac-907d-5856eacf6ab6",
                "accuracy": 3,
                "minVolume": 1e-8,
                "maxVolume": 10001,
                "maxOppositeVolume": 10001,
                "marketOrderPriceThreshold": 10001,
                "isDisabled": false,
                "created": "2020-03-07T12:01:16.959924Z",
                "modified": "2020-03-20T10:46:45.440441Z"
            }
        ]        

### Create a new asset pair [POST]

Create and listing new asset pair.

+ Request (application/json)

    + Headers

                Authorization: Bearer <put your api key>
    
    + Body
    
            {
                "id": "9aea6fd7-42d4-40ac-907d-5856eacf6ee8",
                "name": "BTCETH",
                "baseAssetId": "BTC",
                "quotingAssetId": "8cea5fd7-42d4-40ac-907d-5856eacf6ab6",
                "accuracy": 3,
                "minVolume": 1e-8,
                "maxVolume": 10001,
                "maxOppositeVolume": 10001,
                "marketOrderPriceThreshold": 10001,
                "isDisabled": false
            }

+ Response 200 (application/json)

    + Body

            {
                "id": "9aea6fd7-42d4-40ac-907d-5856eacf6ee8",
                "name": "BTCETH",
                "baseAssetId": "BTC",
                "quotingAssetId": "8cea5fd7-42d4-40ac-907d-5856eacf6ab6",
                "accuracy": 3,
                "minVolume": 1e-8,
                "maxVolume": 10001,
                "maxOppositeVolume": 10001,
                "marketOrderPriceThreshold": 10001,
                "isDisabled": false,
                "created": "2020-03-07T11:52:30.396827Z",
                "modified": "2020-03-07T11:52:30.396827Z"
            }
            
### Update existing Asset [PUT]

Update parameters for the existing asset pair.

+ Request (application/json)

    + Headers

            Authorization: Bearer <put your api key>
    
    + Body
    
            {
                "id": "9aea6fd7-42d4-40ac-907d-5856eacf6ee8",
                "name": "BTCETH",
                "baseAssetId": "BTC",
                "quotingAssetId": "8cea5fd7-42d4-40ac-907d-5856eacf6ab6",
                "accuracy": 3,
                "minVolume": 1e-8,
                "maxVolume": 10001,
                "maxOppositeVolume": 10001,
                "marketOrderPriceThreshold": 10001,
                "isDisabled": false
            }

+ Response 204 (application/json)

### Get Asset [GET/api/asset/public-asset-pairs/{assetPairId}]

Get a asset pair by ID

+ Parameters
    + assetPairId (string) - Asset qniquie ID
    
+ Request
    + Headers

            Authorization: Bearer <put your api key>


+ Response 200 (application/json)

        {
            "id": "9aea6fd7-42d4-40ac-907d-5856eacf6ee8",
            "name": "BTCETH",
            "baseAssetId": "BTC",
            "quotingAssetId": "8cea5fd7-42d4-40ac-907d-5856eacf6ab6",
            "accuracy": 3,
            "minVolume": 1e-8,
            "maxVolume": 10001,
            "maxOppositeVolume": 10001,
            "marketOrderPriceThreshold": 10001,
            "isDisabled": false,
            "created": "2020-03-07T11:52:30.396827Z",
            "modified": "2020-03-07T11:52:30.396827Z"
        }
        
### Delete existing asset pair [DELETE/api/asset/public-asset-pairs/{assetId}]

Delete existing asset pair from exchange

+ Parameters
    + assetId (string) - Asset pair qniquie ID
    
+ Request 
    + Headers

            Authorization: Bearer <put your api key>

+ Response 204

## Limit Order managment [/api/operations/trading/limit-order]

The controller allows a broker to manage limit orders for clients

### Create a new single limit order [POST]

+ Body description
    + walletId: (string) - ID of account for which a limit order is set.
    + assetPairId: (string) - Asset pair ID to make limit order.
    + price: (decimal) - Price of limit order.
    + volume: (decimal) - Volume in base asset for limmit order.
    + type: (string) - The limit order type: `Sell`, `Buy`.

+ Request (application/json)

    + Headers

                Authorization: Bearer <put your api key>
    
    + Body
    
            {
                "walletId": "123333",
                "assetPairId": "BTCUSD",
                "price": 8000,
                "volume": 0.001,
                "type": "Sell"
            }

+ Response 200 (application/json)

    + Body

            {
                "id": "00212c6e-2a5c-4d34-a058-9a46b4279285",
                "status": "Ok",
                "reason": null            
            }
            
### Delete a single limit order [DELETE/api/operations/trading/limit-order/{limitOrderId}]

+ Parameters
    + limitOrderId (string) - Asset Pair unique ID
    
+ Request 
    + Headers

            Authorization: Bearer <put your api key>
            
+ Response 204

## Cash managment [/api/operations/cash-management]

The controller allows a broker to manage balances for clients.

### Increase balance for a client [POST/api/operations/cash-management/cash-in]

+ Body description
    + clientId: (string) - Client ID for which a balance will change.
    + assetId: (string) - Asset ID to change balance.
    + amount: (decimal) - Balance change amount.

+ Request (application/json)

    + Headers

                Authorization: Bearer <put your api key>
    
    + Body
    
            {
                "clientId": "123111",
                "assetId": "BTC",
                "amount": 1.34
            }

+ Response 204 (application/json)

### Decrease balance for a client [POST/api/operations/cash-management/cash-out]

+ Body description
    + clientId: (string) - Client ID for which a balance will change.
    + assetId: (string) - Asset ID to change balance.
    + amount: (decimal) - Balance change amount.
    
+ Request (application/json)

    + Headers

                Authorization: Bearer <put your api key>
    
    + Body
    
            {
                "clientId": "123111",
                "assetId": "BTC",
                "amount": 1.34
            }

+ Response 204 (application/json)

# Market data source [/]

API to receive data about market

## Order book [/api/books/order-books]

Order book it is list of all active orders for AssetPair on exchange.

**Order book structure:**
+ Attributes (object)
    + assetPairId: `8cea5fd7-42d4-40ac-907d-5856eacf6ab6` (string) - Asset pair unique ID. 
    + timestamp: "2020-03-31T09:23:28.241Z" (string) - Last update date and time.
    + limitOrders (array) - Name of base asset in pair.
        + (object)
            + id: `a9aa3ebb-d526-4579-b1bd-007a1e8d840d` (string) - Limit order unique ID.
            + price: 9000.123311 (number) - Limit Order price
            + volume: 10.2231 (number) - Limit Order volume
            + walletId: "client-1131" (string) - Limit Order owner
            + type: "Sell" (string) - Limit Order direction (`Sell`, `Buy`)

### Get all order books [GET]

Return order books for all asset pairs of broker

+ Request (application/json)

    + Headers

            Authorization: Bearer <put your api key>

+ Response 200 (application/json)

    + Body

            {
                {
                    "assetPairId": "a9aa3ebb-d526-4579-b1bd-007a1e8d840d",
                    "timestamp": "2020-03-31T09:23:28.241Z",
                    "limitOrders": [
                      {
                        "id": "a9aa3ebb-d526-4579-b1bd-007a1e8d840d",
                        "price": 9000,
                        "volume": 1,
                        "walletId": "client-1123",
                        "type": "Sell"
                      },
                      {
                        "id": "ab496027-c605-4e3e-82c5-93687b010097",
                        "price": 7000,
                        "volume": 1,
                        "walletId": "client-234",
                        "type": "Buy"
                      }
                    ]
                }
            }
            
### Get order book by specific asset pair [GET/api/books/order-books/{assetPairId}]

Return order books for a specific asset pairs of broker

+ Parameters
    + assetPairId (string) - Asset Pair uniquie ID

+ Request (application/json)

    + Headers

            Authorization: Bearer <put your api key>
            
+ Response 200 (application/json)

    + Body

            {
                "assetPairId": "a9aa3ebb-d526-4579-b1bd-007a1e8d840d",
                "timestamp": "2020-03-31T09:23:28.241Z",
                "limitOrders": [
                  {
                    "id": "a9aa3ebb-d526-4579-b1bd-007a1e8d840d",
                    "price": 9000,
                    "volume": 1,
                    "walletId": "client-1123",
                    "type": "Sell"
                  },
                  {
                    "id": "ab496027-c605-4e3e-82c5-93687b010097",
                    "price": 7000,
                    "volume": 1,
                    "walletId": "client-234",
                    "type": "Buy"
                  }
                ]
            }

    

## Temp [/api/temp]

### Make a access token [POST/api/temp/sign-in]

+ Request (application/json)

    + Body
    
            {
                "email": "admin@admin.com",
                "password": "admin"
            }

+ Response 200 (application/json)

    + Body

            {
                "token": "....."
            }
            
### Get wallet balance [GET/api/operations/temp/balance/{walletId}]

+ Parameters
    + walletId (string) - Asset pair qniquie ID
    
+ Request 

    + Headers

                Authorization: Bearer <put your api key>
    
+ Response 200 (application/json)